---
name: Bundle-SXIP-Homesite
version: 1.0.0
author:
  - Sxip Identity <dev@sxip.org>
abstract: ~
license: bsd
provides:
  Bundle::SXIP::Homesite:
    file: lib/Bundle/SXIP/Homesite.pm
    version: 1.0.0
generated_by: Module::Build version 0.2611
